export const countries = [
    { label: "Afghanistan (+93)", value: "+93", emoji: "🇦🇫" },
    { label: "Albania (+355)", value: "+355", emoji: "🇦🇱" },
    { label: "Algeria (+213)", value: "+213", emoji: "🇩🇿" },
    { label: "Andorra (+376)", value: "+376", emoji: "🇦🇩" },
    { label: "Angola (+244)", value: "+244", emoji: "🇦🇴" },
    { label: "Antigua and Barbuda (+1-268)", value: "+1-268", emoji: "🇦🇬" },
    { label: "Argentina (+54)", value: "+54", emoji: "🇦🇷" },
    { label: "Armenia (+374)", value: "+374", emoji: "🇦🇲" },
    { label: "Australia (+61)", value: "+61", emoji: "🇦🇺" },
    { label: "Austria (+43)", value: "+43", emoji: "🇦🇹" },
    { label: "Azerbaijan (+994)", value: "+994", emoji: "🇦🇿" },
    { label: "Bahamas (+1-242)", value: "+1-242", emoji: "🇧🇸" },
    { label: "Bahrain (+973)", value: "+973", emoji: "🇧🇭" },
    { label: "Bangladesh (+880)", value: "+880", emoji: "🇧🇩" },
    { label: "Barbados (+1-246)", value: "+1-246", emoji: "🇧🇧" },
    { label: "Belarus (+375)", value: "+375", emoji: "🇧🇾" },
    { label: "Belgium (+32)", value: "+32", emoji: "🇧🇪" },
    { label: "Belize (+501)", value: "+501", emoji: "🇧🇿" },
    { label: "Benin (+229)", value: "+229", emoji: "🇧🇯" },
    { label: "Bhutan (+975)", value: "+975", emoji: "🇧🇹" },
    { label: "Bolivia (+591)", value: "+591", emoji: "🇧🇴" },
    { label: "Bosnia and Herzegovina (+387)", value: "+387", emoji: "🇧🇦" },
    { label: "Botswana (+267)", value: "+267", emoji: "🇧🇼" },
    { label: "Brazil (+55)", value: "+55", emoji: "🇧🇷" },
    { label: "Brunei (+673)", value: "+673", emoji: "🇧🇳" },
    { label: "Bulgaria (+359)", value: "+359", emoji: "🇧🇬" },
    { label: "Burkina Faso (+226)", value: "+226", emoji: "🇧🇫" },
    { label: "Burundi (+257)", value: "+257", emoji: "🇧🇮" },
    { label: "Cabo Verde (+238)", value: "+238", emoji: "🇨🇻" },
    { label: "Cambodia (+855)", value: "+855", emoji: "🇰🇭" },
    { label: "Cameroon (+237)", value: "+237", emoji: "🇨🇲" },
    { label: "Canada (+1)", value: "+1", emoji: "🇨🇦" },
    { label: "Central African Republic (+236)", value: "+236", emoji: "🇨🇫" },
    { label: "Chad (+235)", value: "+235", emoji: "🇹🇩" },
    { label: "Chile (+56)", value: "+56", emoji: "🇨🇱" },
    { label: "China (+86)", value: "+86", emoji: "🇨🇳" },
    { label: "Colombia (+57)", value: "+57", emoji: "🇨🇴" },
    { label: "Comoros (+269)", value: "+269", emoji: "🇰🇲" },
    { label: "Congo (+242)", value: "+242", emoji: "🇨🇬" },
    { label: "Costa Rica (+506)", value: "+506", emoji: "🇨🇷" },
    { label: "Côte d'Ivoire (+225)", value: "+225", emoji: "🇨🇮" },
    { label: "Croatia (+385)", value: "+385", emoji: "🇭🇷" },
    { label: "Cuba (+53)", value: "+53", emoji: "🇨🇺" },
    { label: "Cyprus (+357)", value: "+357", emoji: "🇨🇾" },
    { label: "Czech Republic (+420)", value: "+420", emoji: "🇨🇿" },
    { label: "Denmark (+45)", value: "+45", emoji: "🇩🇰" },
    { label: "Djibouti (+253)", value: "+253", emoji: "🇩🇯" },
    { label: "Dominica (+1-767)", value: "+1-767", emoji: "🇩🇲" },
    {
        label: "Dominican Republic (+1-809, +1-829, +1-849)",
        value: "+1-809",
        emoji: "🇩🇴",
    },
    { label: "East Timor (+670)", value: "+670", emoji: "🇹🇱" },
    { label: "Ecuador (+593)", value: "+593", emoji: "🇪🇨" },
    { label: "Egypt (+20)", value: "+20", emoji: "🇪🇬" },
    { label: "El Salvador (+503)", value: "+503", emoji: "🇸🇻" },
    { label: "Equatorial Guinea (+240)", value: "+240", emoji: "🇬🇶" },
    { label: "Eritrea (+291)", value: "+291", emoji: "🇪🇷" },
    { label: "Estonia (+372)", value: "+372", emoji: "🇪🇪" },
    { label: "Ethiopia (+251)", value: "+251", emoji: "🇪🇹" },
    { label: "Fiji (+679)", value: "+679", emoji: "🇫🇯" },
    { label: "Finland (+358)", value: "+358", emoji: "🇫🇮" },
    { label: "France (+33)", value: "+33", emoji: "🇫🇷" },
    { label: "Gabon (+241)", value: "+241", emoji: "🇬🇦" },
    { label: "Gambia (+220)", value: "+220", emoji: "🇬🇲" },
    { label: "Georgia (+995)", value: "+995", emoji: "🇬🇪" },
    { label: "Germany (+49)", value: "+49", emoji: "🇩🇪" },
    { label: "Ghana (+233)", value: "+233", emoji: "🇬🇭" },
    { label: "Greece (+30)", value: "+30", emoji: "🇬🇷" },
    { label: "Grenada (+1-473)", value: "+1-473", emoji: "🇬🇩" },
    { label: "Guatemala (+502)", value: "+502", emoji: "🇬🇹" },
    { label: "Guinea (+224)", value: "+224", emoji: "🇬🇳" },
    { label: "Guinea-Bissau (+245)", value: "+245", emoji: "🇬🇼" },
    { label: "Guyana (+592)", value: "+592", emoji: "🇬🇾" },
    { label: "Haiti (+509)", value: "+509", emoji: "🇭🇹" },
    { label: "Honduras (+504)", value: "+504", emoji: "🇭🇳" },
    { label: "Hungary (+36)", value: "+36", emoji: "🇭🇺" },
    { label: "Iceland (+354)", value: "+354", emoji: "🇮🇸" },
    { label: "India (+91)", value: "+91", emoji: "🇮🇳" },
    { label: "Indonesia (+62)", value: "+62", emoji: "🇮🇩" },
    { label: "Iran (+98)", value: "+98", emoji: "🇮🇷" },
    { label: "Iraq (+964)", value: "+964", emoji: "🇮🇶" },
    { label: "Ireland (+353)", value: "+353", emoji: "🇮🇪" },
    { label: "Israel (+972)", value: "+972", emoji: "🇮🇱" },
    { label: "Italy (+39)", value: "+39", emoji: "🇮🇹" },
    { label: "Jamaica (+1-876)", value: "+1-876", emoji: "🇯🇲" },
    { label: "Japan (+81)", value: "+81", emoji: "🇯🇵" },
    { label: "Jordan (+962)", value: "+962", emoji: "🇯🇴" },
    { label: "Kazakhstan (+7)", value: "+7", emoji: "🇰🇿" },
    { label: "Kenya (+254)", value: "+254", emoji: "🇰🇪" },
    { label: "Kiribati (+686)", value: "+686", emoji: "🇰🇮" },
    { label: "Korea, North (+850)", value: "+850", emoji: "🇰🇵" },
    { label: "Korea, South (+82)", value: "+82", emoji: "🇰🇷" },
    { label: "Kosovo (+383)", value: "+383", emoji: "🇽🇰" },
    { label: "Kuwait (+965)", value: "+965", emoji: "🇰🇼" },
    { label: "Kyrgyzstan (+996)", value: "+996", emoji: "🇰🇬" },
    { label: "Laos (+856)", value: "+856", emoji: "🇱🇦" },
    { label: "Latvia (+371)", value: "+371", emoji: "🇱🇻" },
    { label: "Lebanon (+961)", value: "+961", emoji: "🇱🇧" },
    { label: "Lesotho (+266)", value: "+266", emoji: "🇱🇸" },
    { label: "Liberia (+231)", value: "+231", emoji: "🇱🇷" },
    { label: "Libya (+218)", value: "+218", emoji: "🇱🇾" },
    { label: "Liechtenstein (+423)", value: "+423", emoji: "🇱🇮" },
    { label: "Lithuania (+370)", value: "+370", emoji: "🇱🇹" },
    { label: "Luxembourg (+352)", value: "+352", emoji: "🇱🇺" },
    { label: "Madagascar (+261)", value: "+261", emoji: "🇲🇬" },
    { label: "Malawi (+265)", value: "+265", emoji: "🇲🇼" },
    { label: "Malaysia (+60)", value: "+60", emoji: "🇲🇾" },
    { label: "Maldives (+960)", value: "+960", emoji: "🇲🇻" },
    { label: "Mali (+223)", value: "+223", emoji: "🇲🇱" },
    { label: "Malta (+356)", value: "+356", emoji: "🇲🇹" },
    { label: "Marshall Islands (+692)", value: "+692", emoji: "🇲🇭" },
    { label: "Mauritania (+222)", value: "+222", emoji: "🇲🇷" },
    { label: "Mauritius (+230)", value: "+230", emoji: "🇲🇺" },
    { label: "Mexico (+52)", value: "+52", emoji: "🇲🇽" },
    { label: "Micronesia (+691)", value: "+691", emoji: "🇫🇲" },
    { label: "Moldova (+373)", value: "+373", emoji: "🇲🇩" },
    { label: "Monaco (+377)", value: "+377", emoji: "🇲🇨" },
    { label: "Mongolia (+976)", value: "+976", emoji: "🇲🇳" },
    { label: "Montenegro (+382)", value: "+382", emoji: "🇲🇪" },
    { label: "Morocco (+212)", value: "+212", emoji: "🇲🇦" },
    { label: "Mozambique (+258)", value: "+258", emoji: "🇲🇿" },
    { label: "Myanmar (+95)", value: "+95", emoji: "🇲🇲" },
    { label: "Namibia (+264)", value: "+264", emoji: "🇳🇦" },
    { label: "Nauru (+674)", value: "+674", emoji: "🇳🇷" },
    { label: "Nepal (+977)", value: "+977", emoji: "🇳🇵" },
    { label: "Netherlands (+31)", value: "+31", emoji: "🇳🇱" },
    { label: "New Zealand (+64)", value: "+64", emoji: "🇳🇿" },
    { label: "Nicaragua (+505)", value: "+505", emoji: "🇳🇮" },
    { label: "Niger (+227)", value: "+227", emoji: "🇳🇪" },
    { label: "Nigeria (+234)", value: "+234", emoji: "🇳🇬" },
    { label: "North Macedonia (+389)", value: "+389", emoji: "🇲🇰" },
    { label: "Norway (+47)", value: "+47", emoji: "🇳🇴" },
    { label: "Oman (+968)", value: "+968", emoji: "🇴🇲" },
    { label: "Pakistan (+92)", value: "+92", emoji: "🇵🇰" },
    { label: "Palau (+680)", value: "+680", emoji: "🇵🇼" },
    { label: "Palestine (+970)", value: "+970", emoji: "🇵🇸" },
    { label: "Panama (+507)", value: "+507", emoji: "🇵🇦" },
    { label: "Papua New Guinea (+675)", value: "+675", emoji: "🇵🇬" },
    { label: "Paraguay (+595)", value: "+595", emoji: "🇵🇾" },
    { label: "Peru (+51)", value: "+51", emoji: "🇵🇪" },
    { label: "Philippines (+63)", value: "+63", emoji: "🇵🇭" },
    { label: "Poland (+48)", value: "+48", emoji: "🇵🇱" },
    { label: "Portugal (+351)", value: "+351", emoji: "🇵🇹" },
    { label: "Qatar (+974)", value: "+974", emoji: "🇶🇦" },
    { label: "Romania (+40)", value: "+40", emoji: "🇷🇴" },
    { label: "Russia (+7)", value: "+7", emoji: "🇷🇺" },
    { label: "Rwanda (+250)", value: "+250", emoji: "🇷🇼" },
    { label: "Saint Kitts and Nevis (+1-869)", value: "+1-869", emoji: "🇰🇳" },
    { label: "Saint Lucia (+1-758)", value: "+1-758", emoji: "🇱🇨" },
    {
        label: "Saint Vincent and the Grenadines (+1-784)",
        value: "+1-784",
        emoji: "🇻🇨",
    },
    { label: "Samoa (+685)", value: "+685", emoji: "🇼🇸" },
    { label: "San Marino (+378)", value: "+378", emoji: "🇸🇲" },
    { label: "Sao Tome and Principe (+239)", value: "+239", emoji: "🇸🇹" },
    { label: "Saudi Arabia (+966)", value: "+966", emoji: "🇸🇦" },
    { label: "Senegal (+221)", value: "+221", emoji: "🇸🇳" },
    { label: "Serbia (+381)", value: "+381", emoji: "🇷🇸" },
    { label: "Seychelles (+248)", value: "+248", emoji: "🇸🇨" },
    { label: "Sierra Leone (+232)", value: "+232", emoji: "🇸🇱" },
    { label: "Singapore (+65)", value: "+65", emoji: "🇸🇬" },
    { label: "Slovakia (+421)", value: "+421", emoji: "🇸🇰" },
    { label: "Slovenia (+386)", value: "+386", emoji: "🇸🇮" },
    { label: "Solomon Islands (+677)", value: "+677", emoji: "🇸🇧" },
    { label: "Somalia (+252)", value: "+252", emoji: "🇸🇴" },
    { label: "South Africa (+27)", value: "+27", emoji: "🇿🇦" },
    { label: "South Sudan (+211)", value: "+211", emoji: "🇸🇸" },
    { label: "Spain (+34)", value: "+34", emoji: "🇪🇸" },
    { label: "Sri Lanka (+94)", value: "+94", emoji: "🇱🇰" },
    { label: "Sudan (+249)", value: "+249", emoji: "🇸🇩" },
    { label: "Suriname (+597)", value: "+597", emoji: "🇸🇷" },
    { label: "Sweden (+46)", value: "+46", emoji: "🇸🇪" },
    { label: "Switzerland (+41)", value: "+41", emoji: "🇨🇭" },
    { label: "Syria (+963)", value: "+963", emoji: "🇸🇾" },
    { label: "Taiwan (+886)", value: "+886", emoji: "🇹🇼" },
    { label: "Tajikistan (+992)", value: "+992", emoji: "🇹🇯" },
    { label: "Tanzania (+255)", value: "+255", emoji: "🇹🇿" },
    { label: "Thailand (+66)", value: "+66", emoji: "🇹🇭" },
    { label: "Togo (+228)", value: "+228", emoji: "🇹🇬" },
    { label: "Tonga (+676)", value: "+676", emoji: "🇹🇴" },
    { label: "Trinidad and Tobago (+1-868)", value: "+1-868", emoji: "🇹🇹" },
    { label: "Tunisia (+216)", value: "+216", emoji: "🇹🇳" },
    { label: "Turkey (+90)", value: "+90", emoji: "🇹🇷" },
    { label: "Turkmenistan (+993)", value: "+993", emoji: "🇹🇲" },
    { label: "Tuvalu (+688)", value: "+688", emoji: "🇹🇻" },
    { label: "Uganda (+256)", value: "+256", emoji: "🇺🇬" },
    { label: "Ukraine (+380)", value: "+380", emoji: "🇺🇦" },
    { label: "United Arab Emirates (+971)", value: "+971", emoji: "🇦🇪" },
    { label: "United Kingdom (+44)", value: "+44", emoji: "🇬🇧" },
    { label: "United States (+1)", value: "+1", emoji: "🇺🇸" },
    { label: "Uruguay (+598)", value: "+598", emoji: "🇺🇾" },
    { label: "Uzbekistan (+998)", value: "+998", emoji: "🇺🇿" },
    { label: "Vanuatu (+678)", value: "+678", emoji: "🇻🇺" },
    { label: "Vatican City (+39-06)", value: "+39-06", emoji: "🇻🇦" },
    { label: "Venezuela (+58)", value: "+58", emoji: "🇻🇪" },
    { label: "Vietnam (+84)", value: "+84", emoji: "🇻🇳" },
    { label: "Yemen (+967)", value: "+967", emoji: "🇾🇪" },
    { label: "Zambia (+260)", value: "+260", emoji: "🇿🇲" },
    { label: "Zimbabwe (+263)", value: "+263", emoji: "🇿🇼" },
];

